export const designConfig = {
  layout: {
    pageShell: "min-h-full bg-background p-4 sm:p-6 lg:p-8",
    pageInner: "client-page-shell flex w-full flex-col gap-6",
    pageInnerTight: "client-page-shell flex w-full flex-col gap-5",
    sectionGap: "space-y-6",
    gridGap: "gap-6",
    formGrid: "grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-5",
    twoColumnForm: "flex flex-col lg:flex-row gap-8",
    mainColumn: "flex-[2] space-y-6",
    sideColumn: "lg:w-72 space-y-5 lg:sticky lg:top-6 self-start",
  },
  type: {
    pageTitle: "text-2xl font-bold tracking-tight text-foreground uppercase",
    pageSubtitle: "text-sm text-muted-foreground font-medium",
    sectionTitle: "text-sm font-bold text-foreground uppercase tracking-widest",
    sectionSubtitle: "text-[11px] text-muted-foreground font-black uppercase tracking-widest",
    cardTitle: "text-sm font-bold text-foreground uppercase tracking-widest",
    label: "text-[11px] font-black text-muted-foreground uppercase tracking-widest",
    body: "text-sm font-medium text-foreground",
    helper: "text-xs text-muted-foreground",
    error: "text-[10px] font-bold text-rose-500 uppercase tracking-wider",
    tableText: "text-[13px] font-medium text-foreground",
    tableStrong: "text-[13px] font-bold text-foreground",
    tableMuted: "text-[12px] text-muted-foreground",
    caption: "text-[11px] text-muted-foreground",
  },
  surface: {
    page: "bg-background",
    panel: "bg-card border border-border rounded-sm shadow-sm",
    panelPadded: "p-6",
    panelHeader: "border-b border-border pb-4 mb-6",
    tablePanel: "bg-card rounded-sm border border-border shadow-sm overflow-hidden",
    toolbar: "bg-card border border-border rounded-sm shadow-sm p-3",
    subtle: "bg-muted/30 border border-border rounded-sm",
  },
  control: {
    input: "h-10 w-full border border-input bg-background rounded-sm text-sm focus:ring-2 focus:ring-ring",
    search: "h-10 w-full pl-10 bg-background border border-input rounded-sm text-sm",
    select: "h-10 rounded-sm border-input text-sm",
    button: "rounded-sm text-sm font-bold",
    actionButton: "h-10 gap-2 uppercase tracking-wide text-[12px] font-bold",
    iconButton: "rounded-sm",
    tabs: "rounded-sm text-[13px] font-bold",
    switchRow: "flex items-center justify-between p-4 rounded-sm border border-border bg-muted/30",
  },
  data: {
    tableWrapper: "bg-card rounded-sm border border-border shadow-sm overflow-hidden",
    table: "w-full text-left border-separate border-spacing-0 min-w-[1100px]",
    tableHead: "sticky top-0 z-20 bg-card shadow-sm",
    tableHeadRow: "bg-muted/40 border-b border-border",
    tableHeadCell: "px-5 py-4 text-[11px] font-bold text-muted-foreground uppercase tracking-wider whitespace-nowrap",
    tableBody: "divide-y divide-border",
    tableRow: "group transition-colors even:bg-muted/20 odd:bg-card hover:bg-muted/40",
    tableRowSelected: "bg-primary/10 hover:bg-primary/10",
    tableCell: "px-5 py-4 text-sm text-foreground align-middle",
    pagination: "shrink-0 px-5 py-4 bg-card border-t border-border flex items-center justify-between",
    empty: "px-6 py-20 text-center bg-muted/20 text-muted-foreground",
    loading: "p-16 text-center text-sm font-bold text-muted-foreground animate-pulse uppercase tracking-wide",
  },
  feedback: {
    success: "text-emerald-600 bg-emerald-50 border-emerald-200",
    warning: "text-amber-600 bg-amber-50 border-amber-200",
    danger: "text-rose-600 bg-rose-50 border-rose-200",
    info: "text-primary bg-primary/10 border-primary/20",
    muted: "text-muted-foreground bg-muted border-border",
  },
} as const;

export type DesignConfig = typeof designConfig;
